services:
  postgres:
    image: postgres:17
    container_name: flow-postgres
    
    environment:
      POSTGRES_USER: flowstock
      POSTGRES_PASSWORD: flowstock
      POSTGRES_DB: UsermanagementDb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flow-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ali@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456

    ports:
      - "5050:80"

    depends_on:
      - postgres    

  redis:
    image: redis:latest
    container_name: flow-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data  

  seq:
    image: datalust/seq:latest
    container_name: flowstock-seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "F@rJan9395"
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data    

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: flowstock-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:latest
    container_name: flowstock-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml



volumes:
  postgres-data:
  redis-data:
  seq-data: